// <auto-generated />
using System;
using Lottery.Infrastructure.Database.Ef.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lottery.Infrastructure.Database.Ef.Migrations
{
    [DbContext(typeof(LotteryDbContext))]
    [Migration("20241218024457_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lottery.Domain.Models.Database.Entities.DrawLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DrawHistory");
                });

            modelBuilder.Entity("Lottery.Domain.Models.Database.Entities.DrawNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DrawLogId")
                        .HasColumnType("int");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DrawLogId");

                    b.ToTable("DrawNumbers");
                });

            modelBuilder.Entity("Lottery.Domain.Models.Database.Entities.DrawNumber", b =>
                {
                    b.HasOne("Lottery.Domain.Models.Database.Entities.DrawLog", "DrawLog")
                        .WithMany("DrawNumbers")
                        .HasForeignKey("DrawLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DrawLog");
                });

            modelBuilder.Entity("Lottery.Domain.Models.Database.Entities.DrawLog", b =>
                {
                    b.Navigation("DrawNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
